### ISSUE TITLE
git lfs fetch error

### ISSUE THREAD

**Issue by zakicheung** [TEXflip/sport-court-detection#1]
I got the warining message "batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.", when try to download the pretrained model, is there any other way to got it？

**Comment by TEXflip** [comment]
The problem is that my github account is free and I should pay to allow the download of large files.

The repo was for the Computer Vision course in University of Trento, I can give you the pretrained model in another way if you need it for the project of the course.

**Comment by zakicheung** [comment]
> 

Noted, thank you.
I would appreciate it if you can send me the pretrained model via email. Here's my email address: zaki.cheung@gmail.com
Or if you have more convenient method to provide it, you can also let me know. Thank you very much.

**Comment by BlueDing101** [comment]
Hi thanks for the incredible work. I cannot download pretrained model neither. Could please share the file with me? My mailbox is blueding101@gmail.com. Thank you so much!

**Comment by TEXflip** [comment]
I've removed the model from the repo and moved to a [shared link drive](https://drive.google.com/file/d/1kgPfxeYMSED6bu0xWP-KOSgLDukNPj5t/view?usp=sharing), the link is also in the README. Now you can use the preatrined model, just put it in the pretrained-model directory. 

The issue remains open because you can't get the dataset in the repo, in the future I'll fix this.
